### ISSUE TITLE
Problem running program

### ISSUE THREAD

**Issue by DarkRsing** [parulina/bardmacroplayer#1]
Hey!

I can only make the program run and start playing if I select [these](https://i.imgur.com/Kbc2sJm.png) options. I can't play any .mid at all , it just doesn't do anything when I press play. Have tried over 15 midi's right now

**Comment by parulina** [comment]
Please try a new version i've uploaded [here](https://github.com/parulina/bardmacroplayer/releases/download/untagged-ae54b15b2d3b3a3d5d69/BardMacroPlayer-1.0b.zip). This should fix loading multi-track midis.

The administrator privilege may be necessary, i assume because the program sends keystrokes to the FFXIV window even if it's behind other windows. I don't know how to bypass that check, but if it works, i'd advise to just leave it on.

**Comment by DarkRsing** [comment]
I still doesnt work as intended. I tried loading various midi's from various sources, and it either doesnt work or for some reason separates the files in a lot of options, which I assume are the channels the midi uses. Ive yet to come across a midi that plays correctly. [https://imgur.com/a/pAxUd](url)

**Comment by parulina** [comment]
I assume the note test file works correctly. In which case there may be problems with loading the midi files themselves. Looking at the screenshot, i can tell it's a complicated midi file by the large amount of tracks. Tracks are what usually separates the right/left hand or the instruments. Did you try them all? Some of them may not play until later in the song, or some may be out of the bard's range. The latest version should have a little slider under the stop/play button, this is to adjust the octaves of the midi track when loading it. Adjust it and reload the track (stop button) and see if it plays. If it really doesn't want to play anything at all, feel free to attach the midi file in question and i'll troubleshoot it.

**Comment by DarkRsing** [comment]
Yeah, text files work wondefully , I did try simpler midi's like some Aerith Themes I found online, sadly they seem to sounds very wrong, even with the octave slider.

**Comment by parulina** [comment]
![image](https://user-images.githubusercontent.com/6361957/35850049-e2df64a2-0b23-11e8-9d48-0b1ef587b9d8.png)

I see, the right hand track plays all the way over at C6 which is two steps higher than C4, the maximum octave of the bard. It also plays chords a lot, which will probably make things sound strange. If you have the repository cloned and autohotkey installed, try adding yet another step to the octave slider - pull the latest changes first, then edit BardMacroPlayer.ahk and change this line 
```Gui, Add, Slider, ToolTip Thick10 voctaveShift Range-2-2 x0 y60 w80, 0``` 
to 
```Gui, Add, Slider, ToolTip Thick10 voctaveShift Range-3-3 x0 y60 w80, 0```
experiment with adding more ranges and see if it makes it sound better. If it all fails you may have to edit the midi itself to remove the chords. That's the only thing i can think of since it seems that the midi file is being loaded and parsed correctly.

**Comment by DarkRsing** [comment]
Ill try and check. I'll close this ticket for now and re-open in case I need more help

**Comment by parulina** [comment]
Go to midiParser.ahk line 128 and change this line:
```this.trackNotes[this.trackNumNotes].deltaMs := dms```
to
```this.trackNotes[this.trackNumNotes-1].deltaMs := dms```
I made a typo... to be fair, my sub has run out. This should make things work again.

**Comment by DarkRsing** [comment]
It's working wondefully now, both the extra octave and tempo :D , thank you for support!
