### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Nerdorable** [parulina/bardmacroplayer#4]
Some ideas I've had since playing around with this great little program:

Tempo slider, similar to the octave slider.
Intractable progress bar. If we could click and go to a specific point in the song it would be nice.
Shortcut keys for play, pause, stop, and tempo/octave up or down (would be nice if customizable).

I've been dualboxing to perform duets, so having a shortcut key to press would make the timing of hitting "Play" much more accurate between PCs.

**Comment by pixaline** [comment]
Tempo slider could work, but not in units of BPM (beats per minute) as they get converted to millisecond delays. Could probably do a percentage to slow down/speed up the song from 10% to 200%. Will look in to it
Interactable progress bar should be possible. Will look in to it as well
Customizable shortcut keys is possible. What would be sensible default keys for that? Since switching to perform mode disables all other keys, could probably make use of well known keys such as F1-F4.

I'll work a little on these features.

**Comment by Nerdorable** [comment]
Thank you so much for considering my feature suggestions and working on adding some of them!

**Comment by pixaline** [comment]
Everything was added now. Preparing for v1.3 release. Thank you & closing.
